config/routes.rb
Guthub::Application.routes.draw do
  resources :users

  resources :dishes

  resources :meals
  

  root :to => 'hello#index'

end

app/models/dish.rb
class Dish < ActiveRecord::Base
  attr_accessible :description, :ingredients
  belongs_to :meal
end

app/models/hello.rb
class Hello < ActiveRecord::Base
end

app/models/meal.rb
class Meal < ActiveRecord::Base
  attr_accessible :course, :flavor, :name
  belongs_to :user
  has_many :dishes
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :age, :email, :name
  has_many :meals
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/dishes_controller.rb
class DishesController < ApplicationController
  # GET /dishes
  # GET /dishes.json
  def index
    @dishes = Dish.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @dishes }
    end
  end

  # GET /dishes/1
  # GET /dishes/1.json
  def show
    @dish = Dish.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @dish }
    end
  end

  # GET /dishes/new
  # GET /dishes/new.json
  def new
    @dish = Dish.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @dish }
    end
  end

  # GET /dishes/1/edit
  def edit
    @dish = Dish.find(params[:id])
  end

  # POST /dishes
  # POST /dishes.json
  def create
    @dish = Dish.new(params[:dish])

    respond_to do |format|
      if @dish.save
        format.html { redirect_to @dish, notice: 'Dish was successfully created.' }
        format.json { render json: @dish, status: :created, location: @dish }
      else
        format.html { render action: "new" }
        format.json { render json: @dish.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /dishes/1
  # PUT /dishes/1.json
  def update
    @dish = Dish.find(params[:id])

    respond_to do |format|
      if @dish.update_attributes(params[:dish])
        format.html { redirect_to @dish, notice: 'Dish was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @dish.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dishes/1
  # DELETE /dishes/1.json
  def destroy
    @dish = Dish.find(params[:id])
    @dish.destroy

    respond_to do |format|
      format.html { redirect_to dishes_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/hello_controller.rb
class HelloController < ApplicationController
  
  def index
    @message = "Hello World!"
   # redirect_to "http://www.google.com"
  end
  

  
end

app/controllers/meals_controller.rb
class MealsController < ApplicationController
  # GET /meals
  # GET /meals.json
  def index
    @meals = Meal.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @meals }
    end
  end

  # GET /meals/1
  # GET /meals/1.json
  def show
    @meal = Meal.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @meal }
    end
  end

  # GET /meals/new
  # GET /meals/new.json
  def new
    @meal = Meal.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @meal }
    end
  end

  # GET /meals/1/edit
  def edit
    @meal = Meal.find(params[:id])
  end

  # POST /meals
  # POST /meals.json
  def create
    @meal = Meal.new(params[:meal])

    respond_to do |format|
      if @meal.save
        format.html { redirect_to @meal, notice: 'Meal was successfully created.' }
        format.json { render json: @meal, status: :created, location: @meal }
      else
        format.html { render action: "new" }
        format.json { render json: @meal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /meals/1
  # PUT /meals/1.json
  def update
    @meal = Meal.find(params[:id])

    respond_to do |format|
      if @meal.update_attributes(params[:meal])
        format.html { redirect_to @meal, notice: 'Meal was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @meal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /meals/1
  # DELETE /meals/1.json
  def destroy
    @meal = Meal.find(params[:id])
    @meal.destroy

    respond_to do |format|
      format.html { redirect_to meals_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  def index
    @users = User.all


    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dishes_helper.rb
module DishesHelper
end

app/helpers/hello_helper.rb
module HelloHelper
end

app/helpers/meals_helper.rb
module MealsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/dishes/_form.html.erb
<%= form_for(@dish) do |f| %>
  <% if @dish.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@dish.errors.count, "error") %> prohibited this dish from being saved:</h2>

      <ul>
      <% @dish.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :ingredients %><br />
    <%= f.text_field :ingredients %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/dishes/edit.html.erb
<h1>Editing dish</h1>

<%= render 'form' %>

<%= link_to 'Show', @dish %> |
<%= link_to 'Back', dishes_path %>

app/views/dishes/index.html.erb
<h1>Listing dishes</h1>

<table>
  <tr>
    <th>Ingredients</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @dishes.each do |dish| %>
  <tr>
    <td><%= dish.ingredients %></td>
    <td><%= dish.description %></td>
    <td><%= link_to 'Show', dish %></td>
    <td><%= link_to 'Edit', edit_dish_path(dish) %></td>
    <td><%= link_to 'Destroy', dish, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Dish', new_dish_path %>

app/views/dishes/new.html.erb
<h1>New dish</h1>

<%= render 'form' %>

<%= link_to 'Back', dishes_path %>

app/views/dishes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Ingredients:</b>
  <%= @dish.ingredients %>
</p>

<p>
  <b>Description:</b>
  <%= @dish.description %>
</p>


<%= link_to 'Edit', edit_dish_path(@dish) %> |
<%= link_to 'Back', dishes_path %>

app/views/hello/index.html.erb
<!DOCTYPE html>
<html>
<body>
	<h1><%= @message %></h1>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Guthub</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/meals/_form.html.erb
<%= form_for(@meal) do |f| %>
  <% if @meal.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@meal.errors.count, "error") %> prohibited this meal from being saved:</h2>

      <ul>
      <% @meal.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :course %><br />
    <%= f.text_field :course %>
  </div>
  <div class="field">
    <%= f.label :dishes %><br />
    <%= f.text_field :dishes %>
  </div>
  <div class="field">
    <%= f.label :flavor %><br />
    <%= f.check_box :flavor %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/meals/edit.html.erb
<h1>Editing meal</h1>

<%= render 'form' %>

<%= link_to 'Show', @meal %> |
<%= link_to 'Back', meals_path %>

app/views/meals/index.html.erb
<h1>Listing meals</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Course</th>
    <th>Dishes</th>
    <th>Flavor</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @meals.each do |meal| %>
  <tr>
    <td><%= meal.name %></td>
    <td><%= meal.course %></td>
    <td><%= meal.dishes %></td>
    <td><%= meal.flavor %></td>
    <td><%= link_to 'Show', meal %></td>
    <td><%= link_to 'Edit', edit_meal_path(meal) %></td>
    <td><%= link_to 'Destroy', meal, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Meal', new_meal_path %>

app/views/meals/new.html.erb
<h1>New meal</h1>

<%= render 'form' %>

<%= link_to 'Back', meals_path %>

app/views/meals/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @meal.name %>
</p>

<p>
  <b>Course:</b>
  <%= @meal.course %>
</p>

<p>
  <b>Dishes:</b>
  <%= @meal.dishes %>
</p>

<p>
  <b>Flavor:</b>
  <%= @meal.flavor %>
</p>


<%= link_to 'Edit', edit_meal_path(@meal) %> |
<%= link_to 'Back', meals_path %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :age %><br />
    <%= f.number_field :age %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Age</th>
    <th>Email</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.name %></td>
    <td><%= user.age %></td>
    <td><%= user.email %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @user.name %>
</p>

<p>
  <b>Age:</b>
  <%= @user.age %>
</p>

<p>
  <b>Email:</b>
  <%= @user.email %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>